# Generated by Django 5.1.7 on 2025-05-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('prioridad_visibilidad', models.BooleanField(default=False)),
                ('distintivo', models.CharField(blank=True, max_length=50, null=True)),
                ('verificacion_prioritaria', models.BooleanField(default=False)),
                ('estadisticas', models.BooleanField(default=False)),
                ('precio', models.PositiveIntegerField()),
            ],
        ),
    ]
