# Generated by Django 5.2 on 2025-05-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_alpatex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='prioridad_visibilidad',
            field=models.IntegerField(default=0),
        ),
    ]
