# Generated by Django 5.2 on 2025-06-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_alpatex', '0004_suscripcionmercadopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresia',
            name='plan_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
