# Generated by Django 5.1.7 on 2025-05-21 01:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dm', '0001_initial'),
        ('index', '0011_producto_categoria_alter_perfil_foto_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='canalmensaje',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.producto'),
        ),
        migrations.CreateModel(
            name='ConfirmacionEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dm.canal')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.producto')),
            ],
        ),
    ]
