# Generated by Django 5.1.7 on 2025-05-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dm', '0002_canalmensaje_producto_confirmacionentrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacionentrega',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
