# Generated by Django 5.1.7 on 2025-05-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dm', '0003_confirmacionentrega_confirmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacionentrega',
            name='concretado',
            field=models.BooleanField(default=True),
        ),
    ]
