# Generated by Django 5.1.7 on 2025-04-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_perfil_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
