# Generated by Django 5.2 on 2025-04-27 04:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_producto_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado')], default='Nuevo', max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='estado_revision',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='productos/default_image.jpg', upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='motivo_rechazo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('Venta', 'Venta'), ('Intercambio', 'Intercambio')], default='', max_length=20),
        ),
    ]
