# Generated by Django 5.2 on 2025-04-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_producto_estado_producto_estado_revision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado')], default='', max_length=10),
        ),
    ]
