# Generated by Django 5.1.7 on 2025-05-03 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_alpatex', '0001_initial'),
        ('index', '0007_calificacionproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='membresia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_alpatex.membresia'),
        ),
    ]
