# Generated by Django 5.2 on 2025-04-30 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_alpatex', '0001_initial'),
        ('index', '0008_perfil_membresia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='membresia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_alpatex.membresia'),
        ),
    ]
