# Generated by Django 5.2 on 2025-05-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_perfil_membresia'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='contador_visitas',
            field=models.IntegerField(default=0),
        ),
    ]
