# Generated by Django 5.2 on 2025-05-06 02:47

import index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_producto_contador_visitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='perfil_images/user_defecto.PNG', null=True, upload_to=index.models.user_directory_path),
        ),
    ]
