# Generated by Django 5.2 on 2025-05-08 02:02

import index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_alter_perfil_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Videojuego', 'Videojuego'), ('Libro', 'Libro')], default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=index.models.user_directory_path),
        ),
    ]
