# Generated by Django 5.1.7 on 2025-05-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_calificacionvendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
