# Generated by Django 5.0.6 on 2025-05-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_reportevendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='favoritos', to='index.producto'),
        ),
    ]
