# Generated by Django 5.1.7 on 2025-05-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_perfil_favoritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportevendedor',
            name='puntaje',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
