# Generated by Django 5.2 on 2025-05-29 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_remove_reportevendedor_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportevendedor',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.producto'),
        ),
    ]
