# Generated by Django 5.2 on 2025-05-29 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_reportevendedor_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportevendedor',
            name='producto',
        ),
    ]
