# Generated by Django 5.0.6 on 2025-05-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_remove_reportevendedor_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='motivo_eliminacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
