# Generated by Django 5.2 on 2025-06-06 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_calificacioncliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportevendedor',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportevendedor',
            name='puntaje',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
