# Generated by Django 5.2 on 2025-06-09 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_reportevendedor_producto_reportevendedor_puntaje_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporteusuario',
            name='comprador',
        ),
        migrations.RemoveField(
            model_name='reporteusuario',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='reporteusuario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
