# Generated by Django 5.2 on 2025-06-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_remove_reporteusuario_comprador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
